export const SIDEBAR_CLOSE = 'SIDEBAR_CLOSE';
export const SIDEBAR_TOGGLE = 'SIDEBAR_TOGGLE';
export const LOGOUT_MODAL_OPEN = 'LOGOUT_MODAL_OPEN';
export const LOGOUT_MODAL_CLOSE = 'LOGOUT_MODAL_CLOSE';
